export const RouteBase = {

  Login: '/login',
  Register: '/register',
  Test: '/test',
  OrderManage: '/order-manage',
  ProductManage: '/product-manage',
  Profile: '/profile',
  Home: '/',
  Product: '/catalog/:slug',
  Cart: '/cart',
  Catalog: '/catalog',
  Payment: '/payment',
  Support: '/support',
  ProfileUser: "/user",
  CatalogManage: "/catalog-manage",
  Chat: '/chat',
  ProfileUserTab: '/user/profile',
  OrderUser: '/user/orders',
  NotiUser: '/user/noti',
};
